# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Aardvark.Rendering'
tagline:          'rendering things'
description:      ''
url:              https://vrvis.github.io/aardvark.rendering
baseurl:          /

author:
  name:           'FsBlog'
  url:            

paginate:         5

github:
  repo:           https://github.com/vrvis/aardvark.rendering
