# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Aardvark.Rendering'
tagline:          'rendering things'
description:      ''
url:              https://vrvis.github.io
baseurl:          /aardvark.rendering

author:
  name:           'VRVis'
  url:            

paginate:         5

github:
  repo:           https://github.com/vrvis/aardvark.rendering
